Revert "fair.c fix error ../kernel/sched/fair.c:5612:6: error: use of undeclared identifier 'task_sleep'"
This reverts commit 6a8a88efe0ea3efe0d6079f8f24d53814f83ddd4.