Revert "sysctl.c fix error ../kernel/sysctl.c:192:13: error: conflicting types for ‘three’; have ‘uint’ {aka ‘unsigned int’} from https://github.com/Siarrrrrrrr/fog-kribo-157/commit/2d4b0942a4522fa28be71d2c68090a0908ecb24e"
This reverts commit e66717b4f55ce862f1085f5b4e5cd5c9a5c7c6f6.